version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"

    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    container_name: hello-front-dev
