version: '3.8'

services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    container_name: todo-frontend-dev

  nginx:
    image: nginx:1.20.1
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
