version: '3.8'

services:
  frontend:
    build:
      context: ./note-app-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - noteapp-network
    volumes:
      - ./note-app-frontend:/app

  backend:
    build:
      context: ./note-app-backend
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    networks:
      - noteapp-network
    volumes:
      - ./note-app-backend:/app


networks:
  noteapp-network:
    driver: bridge
