version: '3.8'

services:
  frontend:
    build:
      context: ./note-app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - noteapp-network

  backend:
    build:
      context: ./note-app-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - noteapp-network

networks:
  noteapp-network:
    driver: bridge
